swagger: '2.0'
info:
  title: User Management API
  description: API to manage user operations
  version: 1.0.0
host: "" # gateway [managed services]
x-google-backend:
  address: "" # backend [cloud function]
basePath: "/"
schemes:
  - https
  - http
produces:
  - application/json
paths:
  /users:
    get:
      summary: Retrieve a user by ID
      operationId: getUser
      parameters:
        - name: id
          in: query
          required: true
          type: string
      responses:
        '200':
          description: User retrieved successfully.
        '404':
          description: User not found.
    post:
      summary: Create a new user
      consumes:
        - application/json
      operationId: createUser
      parameters:
        - in: body
          name: user
          description: User to add
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
      responses:
        '201':
          description: User created.
        '400':
          description: Invalid input.
  /users/{id}:
    put:
      summary: Update an existing user
      consumes:
        - application/json
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: user
          description: User information to update
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
      responses:
        '200':
          description: User updated successfully.
        '404':
          description: User not found.
    delete:
      summary: Delete a user
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: User deleted successfully.
        '404':
          description: User not found.
securityDefinitions:
  api_key:
    type: apiKey
    in: query
    name: Key
security:
  - api_key: []